# NAMA : THUFAIL BINTANG KASTELLA
#NPM : 5210411185


##############----SET----##############
# UNION


# Membuat set A and B 
A = {1, 2, 3, 4, 5} 
B = {4, 5, 6, 7, 8} 

# Gabungan menggunakan operator | 
# output: {1, 2, 3, 4, 5, 6, 7, 8} 
print(A | B) 

# Menggunakan fungsi union() 
# output: {1, 2, 3, 4, 5, 6, 7, 8} 
A.union(B) 

# output: {1, 2, 3, 4, 5, 6, 7, 8} 
B.union(A) 